name: Generate Release Artifacts

on:
  release:
    types:
      - created

jobs:
  release:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # right now we only build on linux due to needing OS libraries available
        # if you can think of a way to spew out macOS and Windows binaries, please submit a PR!
        goos: [linux]
        goarch: ["386", amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.19"
          pre_command: "apt-get update && apt-get install libudev-dev libusb-1.0-0-dev"
          project_path: "./cmd/fsbeacon"
          binary_name: "fsbeacon"
          extra_files: LICENSE README.md