name: Generate Release Artifacts

on:
  release:
    types:
      - created

jobs:
  release:
    name: Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            os: macos-latest
          - goarch: arm64
            os: windows-latest
        include:
          - os: ubuntu-latest
            prepare: |
              sudo apt-get update
              sudo apt-get install libudev-dev libusb-1.0-0-dev
            goos: linux
          - os: macos-latest
            goos: darwin
          - os: windows-latest
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: ${{ matrix.prepare }}
        run: ${{ matrix.prepare }}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.19"
          project_path: "./cmd/fsbeacon"
          binary_name: "fsbeacon"
          extra_files: LICENSE README.md